# Generated by Django 3.0.5 on 2021-11-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='quote',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Favourite Quote'),
        ),
    ]
