# Generated by Django 3.0.5 on 2021-11-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20211103_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='Finished'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(default='No Title', max_length=100, verbose_name='Title'),
        ),
    ]
