# Generated by Django 3.0.5 on 2021-11-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20211103_2141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(default=None, max_length=100, verbose_name='Title'),
        ),
    ]
