# Generated by Django 3.0.5 on 2021-11-04 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20211104_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='success',
            field=models.BooleanField(default=False, verbose_name='Success'),
        ),
    ]
